### ISSUE TITLE
Bildirim erişimi

### ISSUE THREAD

**Issue by mahmutuslu** [suat074/MA-XML-12-TURKISH#2]
Tekrar selam üstad

AKıllı saati tanıtırken bildirime erişime izin vermek gerekiyor türkçe kullanırken bu izni veremiyorsun hata veriyor bilgine

**Comment by altiner** [comment]
> Tekrar selam üstad
> 
> AKıllı saati tanıtırken bildirime erişime izin vermek gerekiyor türkçe kullanırken bu izni veremiyorsun hata veriyor bilgine

dili ingilizce yapınca geçici olarak problem çözülüyor.

**Comment by suatsari** [comment]
Bu sorunu düzelttim, yeni sürümde sorunsuz kullanabilirsiniz.

**Comment by mahmutuslu** [comment]
Bu sorun çözüldü teşekkürler
