### ISSUE TITLE
Derin temizleme uygulaması küçük çeviri hatası

### ISSUE THREAD

**Issue by LatifSC** [suat074/MA-XML-12-TURKISH#27]
Merhaba. Cihazın depolama alanı dolduğunda gelen uyarı kutusunda "Temizle" yerine "Tamizle" yazıyor. Pek çok kişi telefonun depolama alanını doldurmadığı için fark edilmedi sanırım. Kolay gelsin. 
![IMG_20200716_014232](https://user-images.githubusercontent.com/68355853/87607272-a11cbb00-c705-11ea-9c0a-46089d24677d.jpg)

**Comment by LatifSC** [comment]
Bu arada kullandığım sürüm MIUI 12.1 Beta 20.7.9. Cihaz ise Redmi Note 8.

**Comment by suat074** [comment]
> Merhaba. Cihazın depolama alanı dolduğunda gelen uyarı kutusunda "Temizle" yerine "Tamizle" yazıyor. Pek çok kişi telefonun depolama alanını doldurmadığı için fark edilmedi sanırım.

Doğrudur hocam, düzeltildi teşekkürler :)

**Comment by LatifSC** [comment]
> > Merhaba. Cihazın depolama alanı dolduğunda gelen uyarı kutusunda "Temizle" yerine "Tamizle" yazıyor. Pek çok kişi telefonun depolama alanını doldurmadığı için fark edilmedi sanırım.
> 
> Doğrudur hocam, düzeltildi teşekkürler :)

Ben teşekkür ederim :)
