### ISSUE TITLE
VPN

### ISSUE THREAD

**Issue by altiner** [suat074/MA-XML-12-TURKISH#3]
VPN profili eklemeye çalışınca onay butonu çalışmıyor. mi8

**Comment by altiner** [comment]
> VPN profili eklemeye çalışınca onay butonu çalışmıyor.

Mi8de

**Comment by emrekrks0** [comment]
tam ekran haraketlerini devre dışı bırak öyle dene

**Comment by altiner** [comment]
> tam ekran haraketlerini devre dışı bırak öyle dene

çok saol🙏👍
